
package com.cafe.gui;

import com.formdev.flatlaf.FlatClientProperties;

public class InvoiceItemCard extends javax.swing.JPanel {

    private SalesChannel salesChannel; 
    
    private int id;
    private String itemName;
    private double price;
    private double quantity; 
    private double discount;
    private String brand;

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    public double getDiscount() {
        return discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
        jLabel1.setText("<html><p>"+itemName);        
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
        jLabel3.setText(String.valueOf(price));
    }

    public double getQuantity() {
        return quantity;
    }

    public void setQuantity(double quantity) {
        this.quantity = quantity;
        jButton2.setText(String.valueOf(quantity));
    }
    
    public void setTotal(Double total){
        jLabel2.setText(String.valueOf(total));
    }
    
    public double getTotal(){
        return Double.parseDouble(jLabel2.getText());
    }       
    public void setSalesChannel(SalesChannel salesChannel) {
        this.salesChannel = salesChannel;
    }
    /**
     * Creates new form InvoiceItemCard
     */
    public InvoiceItemCard() {
        initComponents();
        jButton2.putClientProperty(FlatClientProperties.STYLE,"arc:100");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(490, 60));
        setMinimumSize(new java.awt.Dimension(490, 60));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(490, 60));
        setLayout(new java.awt.BorderLayout());
        add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 5, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(245, 57));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 57));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("<html><p>Cheese and chicken max double burger");
        jLabel1.setMinimumSize(new java.awt.Dimension(45, 57));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 57));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(20, 0));

        jButton2.setBackground(new java.awt.Color(77, 120, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("33");
        jButton2.setBorderPainted(false);
        jButton2.setMargin(new java.awt.Insets(2, 3, 3, 3));
        jButton2.setPreferredSize(new java.awt.Dimension(40, 27));
        jPanel3.add(jButton2, java.awt.BorderLayout.LINE_END);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("750.00");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 5));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(20, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(77, 120, 204));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, java.awt.BorderLayout.LINE_END);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("1500.00");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.salesChannel.removeInvoiceItem(this);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
