/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.gui;

import com.cafe.model.Mysql;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Settings extends javax.swing.JPanel {

    private Dashboard dashboard;

    public Dashboard getDashboard() {
        return dashboard;
    }

    public void setDashboard(Dashboard dashboard) {
        this.dashboard = dashboard;
    }
    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel72 = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel79 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel48 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSSINESS DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel60.setLayout(new java.awt.BorderLayout(15, 15));

        jPanel61.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel61.setLayout(new java.awt.BorderLayout());

        jPanel64.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Resturant Name");
        jLabel4.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel64.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField3.setText("Samanmal");
        jTextField3.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel64.add(jTextField3, java.awt.BorderLayout.PAGE_END);

        jPanel61.add(jPanel64, java.awt.BorderLayout.CENTER);

        jPanel60.add(jPanel61, java.awt.BorderLayout.PAGE_START);

        jPanel65.setLayout(new java.awt.BorderLayout());

        jPanel66.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel66.setLayout(new java.awt.BorderLayout());

        jPanel71.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Telephone");
        jLabel5.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel71.add(jLabel5, java.awt.BorderLayout.CENTER);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField4.setText("0412345678");
        jTextField4.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel71.add(jTextField4, java.awt.BorderLayout.PAGE_END);

        jPanel66.add(jPanel71, java.awt.BorderLayout.CENTER);

        jPanel65.add(jPanel66, java.awt.BorderLayout.PAGE_START);

        jPanel72.setPreferredSize(new java.awt.Dimension(37, 80));
        jPanel72.setLayout(new java.awt.BorderLayout());

        jPanel73.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel73.setLayout(new java.awt.BorderLayout());

        jPanel78.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Address");
        jLabel6.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel78.add(jLabel6, java.awt.BorderLayout.CENTER);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField5.setText("No 23/2 Colombo ,02");
        jTextField5.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel78.add(jTextField5, java.awt.BorderLayout.PAGE_END);

        jPanel73.add(jPanel78, java.awt.BorderLayout.CENTER);

        jPanel72.add(jPanel73, java.awt.BorderLayout.PAGE_START);

        jPanel79.setPreferredSize(new java.awt.Dimension(580, 134));
        jPanel79.setLayout(new java.awt.BorderLayout());

        jPanel80.setPreferredSize(new java.awt.Dimension(580, 134));
        jPanel80.setLayout(new java.awt.BorderLayout());

        jPanel20.setPreferredSize(new java.awt.Dimension(70, 40));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel21.setPreferredSize(new java.awt.Dimension(70, 40));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jButton3.setBackground(new java.awt.Color(77, 120, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SAVE");
        jButton3.setBorderPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel21.add(jButton3, java.awt.BorderLayout.SOUTH);

        jPanel20.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel80.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel79.add(jPanel80, java.awt.BorderLayout.CENTER);

        jPanel72.add(jPanel79, java.awt.BorderLayout.CENTER);

        jPanel65.add(jPanel72, java.awt.BorderLayout.CENTER);

        jPanel60.add(jPanel65, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel60, java.awt.BorderLayout.CENTER);

        add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADMIN DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel9.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel10.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("First Name");
        jLabel1.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel13.add(jLabel1, java.awt.BorderLayout.CENTER);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField1.setText("Sahan");
        jTextField1.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel13.add(jTextField1, java.awt.BorderLayout.PAGE_END);

        jPanel10.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel14.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel15.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Last Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel18.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField2.setText("Perera");
        jTextField2.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel18.add(jTextField2, java.awt.BorderLayout.PAGE_END);

        jPanel15.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(77, 120, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, java.awt.BorderLayout.SOUTH);

        jPanel19.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "SYSTEM SETTINGS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 14)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel36.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel37.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel37.setLayout(new java.awt.BorderLayout());

        jPanel40.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Select Default Theme");
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel40.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel37.add(jPanel40, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel37, java.awt.BorderLayout.PAGE_START);

        jPanel41.setLayout(new java.awt.BorderLayout());

        jPanel42.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel42.setLayout(new java.awt.BorderLayout());

        jPanel47.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButton1.setText("Dark Mode");
        jRadioButton1.setPreferredSize(new java.awt.Dimension(98, 40));
        jPanel47.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRadioButton2.setText("Light Mode");
        jRadioButton2.setPreferredSize(new java.awt.Dimension(98, 40));
        jPanel47.add(jRadioButton2);

        jPanel42.add(jPanel47, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel42, java.awt.BorderLayout.PAGE_START);

        jPanel48.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel48.setLayout(new java.awt.BorderLayout());

        jPanel51.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel51.setLayout(new java.awt.BorderLayout());

        jPanel22.setLayout(new java.awt.BorderLayout());

        jButton4.setBackground(new java.awt.Color(77, 120, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SAVE");
        jButton4.setBorderPainted(false);
        jButton4.setPreferredSize(new java.awt.Dimension(75, 40));
        jPanel22.add(jButton4, java.awt.BorderLayout.SOUTH);

        jPanel51.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel48.add(jPanel51, java.awt.BorderLayout.CENTER);

        jPanel41.add(jPanel48, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel41, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel36, java.awt.BorderLayout.CENTER);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String fname = jTextField1.getText();
        String lname = jTextField2.getText();
        
        if (fname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your First Name", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (lname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Last name", "Warning", JOptionPane.WARNING_MESSAGE);

        } else{
        
            
            try {
                 Mysql.execute("SELECT * FROM `user` INNER JOIN `user_role` "
                    + "ON `user`.`user_role_id` = `user_role`.`id` "
                    + "INNER JOIN `active_state` ON `user`.`active_state_state_id`=`active_state`.`state_id` WHERE `mobile` LIKE '%%' ");
                
                
                     
                    
                

            } catch (Exception e) {
                e.printStackTrace();
            }
        
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
