
package com.cafe.gui;

import com.cafe.model.User;
import com.cafe.style.CustomStyle;
import com.cafe.style.Pallet;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.*;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

public class Splash extends javax.swing.JFrame {

    public static Logger logger = Logger.getLogger("cafe");

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        initializeLogger();
        CustomStyle.setIcon(this);
        animateLoading();
    }

    private void initializeLogger() {
        try {
            FileHandler fileHandler = new FileHandler("cafe.log", true);
            fileHandler.setFormatter(new SimpleFormatter());
            logger.addHandler(fileHandler);
        } catch (IOException ex) {
            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Logger initialization faild - IOException");
        } catch (SecurityException ex) {
            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Logger Initialization faild - SecurityException");
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Logger initialization faild - IllegalArgumentException");
        }
    }

    public void setThemeSelection(User user) {
        this.dispose();
        new ThemeSelection(user).setVisible(true);
    }

    public void setDashboard(User user) {
        if (user != null) {
            this.dispose();
            Dashboard dashboard = new Dashboard(user);
            Pallet.setDashboard(dashboard);
            dashboard.setComponentTheme();
            dashboard.setVisible(true);
        }
    }

    private void animateLoading() {
        new Thread(() -> {
            int width = getWidth();
            animateProgressbar();
            animateFrameFadeOut();
            setLogin();
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                logger.log(Level.WARNING, null, ex);
            }
            animateFrameFadeIn(width);
        }).start();
    }

    private void animateProgressbar() {
        for (int i = 0; i <= 100; i++) {
            jProgressBar1.setValue(i);
            jLabel2.setText(i + "%");
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                logger.log(Level.WARNING, null, ex);
            }
        }
    }

    private void animateFrameFadeOut() {
        float opacity = getOpacity();

        for (int i = getWidth(); i >= 0; i -= 30) {
            setSize(new Dimension(i, getHeight()));

            if (opacity >= 0.1) {
                setOpacity(opacity -= 0.1);
            } else {
                setOpacity(0);
            }
            setLocationRelativeTo(null);
            revalidate();
            try {
                Thread.sleep(1);
            } catch (InterruptedException ex) {
                logger.log(Level.WARNING, null, ex);
            }
        }
    }

    private void animateFrameFadeIn(int width) {
        setSize(new Dimension(width, getHeight()));
        setLocationRelativeTo(null);
        revalidate();

        for (float i = 0; i <= 1.0; i += 0.1) {
            setOpacity(i);
            try {
                Thread.sleep(19);
            } catch (InterruptedException ex) {
                logger.log(Level.WARNING, null, ex);
            }
        }
        setOpacity(1);
    }

    private void setLogin() {
        jPanel1.removeAll();
        Login login = new Login();
        login.setSplash(this);
        jPanel1.add(login);
        SwingUtilities.updateComponentTreeUI(jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(992, 637));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(992, 637));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 120, 204), 1, true));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel2.setBackground(new java.awt.Color(77, 120, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 20, 30));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CAFE-POS");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Restaurant Management System");
        jPanel2.add(jLabel4, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 25, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(992, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jProgressBar1.setForeground(new java.awt.Color(77, 120, 204));
        jProgressBar1.setValue(20);
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 30));
        jPanel3.add(jProgressBar1, java.awt.BorderLayout.SOUTH);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 120, 204));
        jLabel2.setText("0%");
        jPanel3.add(jLabel2, java.awt.BorderLayout.EAST);

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 120, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Openning...");
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/img/ezgif-6-7abd067855.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatDarkLaf look and feel */
        FlatLightLaf.setup();
        UIManager.put( "ScrollBar.showButtons", true );
        CustomStyle.showRevealButton();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
