/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.gui;

import com.cafe.model.Mysql;
import com.cafe.model.SupplierBean;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.cafe.gui.SingleSupplier;
import java.awt.BorderLayout;
import javax.swing.SwingUtilities;


/**
 *
 * @author User
 */
public class Suppliermain extends javax.swing.JPanel {
    
    private Frame LoadSuppliers;
    private static String email;
    private String mobile;

    private SupplierBean supplierBean = new SupplierBean();
    private static Logger log;
    private static FileHandler fileHandler;
   
    static {
        try {

            log = Logger.getLogger("log");
            fileHandler = new FileHandler("log.txt", true);
            fileHandler.setFormatter(new SimpleFormatter());
            log.addHandler(fileHandler);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private Frame SingleSupplier;
   
    public Suppliermain() {
        initComponents();
        loadSupplier();
       
    }
    
    private void search() {

        try {
            Vector vector = new Vector();
            ResultSet resultSet = Mysql.execute("SELECT `name` FROM `supplier_category` ");

            while (resultSet.next()) {

                String category = resultSet.getString("supplier_category.name");

                vector.add(category);

            }

            DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) jComboBox3.getModel();

            comboBoxModel.addAll(vector);

        } catch (Exception e) {
            e.printStackTrace();

        }

    }

    private void search1() {
        try {
            Vector vector = new Vector();
            ResultSet resultSet = Mysql.execute("SELECT `name` FROM `payment_method` ");

            while (resultSet.next()) {

                String payment = resultSet.getString("payment_term");

                vector.add(payment);
            }

            DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) jComboBox1.getModel();
            comboBoxModel.addAll(vector);
        } catch (Exception e) {

        }

    }
    
     private void loadSupplier() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            ResultSet resultSet = Mysql.execute("SELECT * FROM `supplier` INNER JOIN `supplier_category` "
                    + "ON `supplier`.`supplier_category_id` = `supplier_category`.`id` WHERE `mobile` LIKE '%%' ");

            while (resultSet.next()) {

                Vector vector = new Vector<>();
                vector.add(resultSet.getString("name"));
                vector.add(resultSet.getString("mobile"));
                vector.add(resultSet.getString("email"));
                vector.add(resultSet.getString("supplier_category.name"));
                vector.add(resultSet.getString("payment_term"));

                model.addRow(vector);

            }
        } catch (Exception e) {

        }

    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel20 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(194, 54));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 460));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 15));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 90));
        jPanel2.setLayout(new java.awt.BorderLayout(20, 0));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filter by Category", "Vegetable", "Fruits", "Soft Drinks", " " }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(72, 40));
        jComboBox2.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel3.add(jComboBox2, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Search Name | Mobile");
        jLabel2.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(72, 40));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 15));

        jPanel8.setPreferredSize(new java.awt.Dimension(940, 70));
        jPanel8.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jPanel6.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField2.setText("Sahani");
        jTextField2.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel6.add(jTextField2, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel7.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mobile");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField4.setText("0758144382");
        jTextField4.setPreferredSize(new java.awt.Dimension(72, 40));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel7.add(jTextField4, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel7);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel9.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Email");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setPreferredSize(new java.awt.Dimension(72, 40));
        jPanel9.add(jLabel3, java.awt.BorderLayout.CENTER);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField3.setText("sahani@gmail.com");
        jTextField3.setPreferredSize(new java.awt.Dimension(72, 40));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField3, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel9);

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel11.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jPanel12.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel12.setLayout(new java.awt.BorderLayout(5, 5));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Vegetable", "Fruits", "Softdrinks" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(72, 32));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox3, java.awt.BorderLayout.PAGE_START);

        jPanel11.add(jPanel12);
        jPanel11.add(jPanel20);

        jPanel13.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Methods", "Cash", "Card" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(72, 32));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel13.add(jComboBox1, java.awt.BorderLayout.PAGE_START);

        jPanel11.add(jPanel13);

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel14.setLayout(new java.awt.BorderLayout(5, 10));

        jPanel15.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanel15.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel16.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("Add Supplier");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16, java.awt.BorderLayout.LINE_START);

        jPanel17.setPreferredSize(new java.awt.Dimension(270, 100));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton4.setText("Check Due Payments");
        jButton4.setPreferredSize(new java.awt.Dimension(160, 28));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel17, java.awt.BorderLayout.LINE_END);

        jPanel18.setPreferredSize(new java.awt.Dimension(280, 100));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(75, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        jPanel19.setLayout(new java.awt.BorderLayout(5, 5));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Mobile", "Email", "Category", "Payment Term"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel19.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jPanel14.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String mobile = jTextField4.getText();

            try {
                ResultSet resultSet = Mysql.execute("SELECT * FROM  `supplier` WHERE `mobile` = '" + mobile + "'");
                if (resultSet.next()) {
                    String name = resultSet.getString("name");
                    String Email = resultSet.getString("email");
                    String category = resultSet.getString("supplier_category.name");
                    String payment = resultSet.getString("payment_term");

                    supplierBean.setName(name);
                    supplierBean.setMobile(mobile);
                    supplierBean.setEmail(Email);
                    supplierBean.setCategory(category);
                    supplierBean.setPayment(payment);

                    jTextField2.setText(name);
                    jTextField4.setText(mobile);
                    jTextField3.setText(Email);
                    jComboBox3.setSelectedItem(String.valueOf(category));
                    jComboBox1.setSelectedItem(String.valueOf(payment));

                } else {
                    supplierBean.setName("None");
                    supplierBean.setMobile("None");
                    supplierBean.setEmail("None");
                    supplierBean.setCategory(0);
                    supplierBean.setPayment("None");

                    jTextField2.setText("");
                    jTextField4.setText("");
                    jTextField3.setText("");
                    jComboBox3.setSelectedItem(String.valueOf(0));
                    jComboBox1.setSelectedItem(String.valueOf(0));

                }

            } catch (Exception e) {
                log = Logger.getLogger("log");
                try {
                    fileHandler = new FileHandler("mobile.txt", true);
                } catch (IOException ex) {
                    Logger.getLogger(Suppliermain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SecurityException ex) {
                    Logger.getLogger(Suppliermain.class.getName()).log(Level.SEVERE, null, ex);
                }
                fileHandler.setFormatter(new SimpleFormatter());
                log.addHandler(fileHandler);
            }

        }
        
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField2.getText();
        String mobile = jTextField4.getText();
        String email = jTextField3.getText();
        String category = String.valueOf(jComboBox3.getSelectedIndex());
        String paymentMethod = String.valueOf(jComboBox1.getSelectedItem());

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Name", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Mobile", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Email", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!email.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@"
                + "[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {

            JOptionPane.showMessageDialog(this, "Invalid Email", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if ("Select Category".equals(category)) {
            JOptionPane.showMessageDialog(this, "Please Select Category", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (paymentMethod.equals("Select Payment Methods")) {
            JOptionPane.showMessageDialog(this, "Please Select Your Payment Method", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                ResultSet resultSet = Mysql.execute("SELECT * FROM `supplier` WHERE `name` = '" + name + "' OR `mobile` = '" + mobile + "' OR `email` = '" + email + "'");

                if (resultSet.next()) {
                    JOptionPane.showMessageDialog(this, "Supplier Already Registered", "Warning", JOptionPane.WARNING_MESSAGE);

                } else {
                    Mysql.execute("INSERT INTO `supplier` (`name`,`mobile`,`email`,`payment_term`,`supplier_category_id`) "
                            + "VALUES ('" + name + "','" + mobile + "','" + email + "','" + paymentMethod + "','" + category + "')");

                    loadSupplier();

                }

            } catch (Exception e) {

                log = Logger.getLogger("log");
                try {
                    fileHandler = new FileHandler("RegisterSupllier.txt", true);
                } catch (IOException ex) {
                    Logger.getLogger(Suppliermain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SecurityException ex) {
                    Logger.getLogger(Suppliermain.class.getName()).log(Level.SEVERE, null, ex);
                }
                fileHandler.setFormatter(new SimpleFormatter());
                log.addHandler(fileHandler);
            }

        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();

        jTextField2.setText(String.valueOf(jTable1.getValueAt(row, 0)));
        jTextField4.setText(String.valueOf(jTable1.getValueAt(row, 1)));
        jTextField3.setText(String.valueOf(jTable1.getValueAt(row, 2)));
         
        jComboBox3.setSelectedItem(String.valueOf(jTable1.getValueAt(row, 3)));
        jComboBox1.setSelectedItem(String.valueOf(jTable1.getValueAt(row, 4)));
        // select Table
        
       
       
           
           
          
        
        
        

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name = jTextField2.getText();
        String mobile = jTextField4.getText();
        String email = jTextField3.getText();
        int category = Integer.valueOf(jComboBox3.getSelectedIndex());
        String paymentMethod = String.valueOf(jComboBox1.getSelectedItem());

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Name", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (mobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Mobile", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!mobile.matches("^07[01245678]{1}[0-9]{7}$")) {
            JOptionPane.showMessageDialog(this, "Invalid Mobile Number", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Your Email", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!email.matches("^(?=.{1,64}@)[A-Za-z0-9\\+_-]+(\\.[A-Za-z0-9\\+_-]+)*@"
                + "[^-][A-Za-z0-9\\+-]+(\\.[A-Za-z0-9\\+-]+)*(\\.[A-Za-z]{2,})$")) {

            JOptionPane.showMessageDialog(this, "Invalid Email", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if ("Select Category".equals(category)) {
            JOptionPane.showMessageDialog(this, "Please Select Category", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (paymentMethod.equals("Select Payment Methods")) {
            JOptionPane.showMessageDialog(this, "Please Select Your Payment Method", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                ResultSet resultSet = Mysql.execute("SELECT * FROM `supplier` WHERE `mobile` = '" + mobile + "'");
                boolean canupdate = false;
                if (resultSet.next()) {
                    if (resultSet.getString("mobile").equals(mobile)) {
                        canupdate = true;
                    } else {
                        JOptionPane.showMessageDialog(this, "Mobile Already Used", "Warning", JOptionPane.WARNING_MESSAGE);

                    }

                } else {
                    canupdate = true;

                }
                if (canupdate) {
                    Mysql.execute("UPDATE `supplier` "
                            + "SET `name`= '" + name + "',"
                            + "`email`='" + email + "',"
                            + "`payment_term`='" + paymentMethod + "' WHERE `mobile` = '" + mobile + "' ");

                    loadSupplier();
                }

            } catch (Exception e) {
                log = Logger.getLogger("log");
                try {
                    fileHandler = new FileHandler("updateSupplier.txt", true);
                } catch (IOException ex) {
                    Logger.getLogger(Suppliermain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SecurityException ex) {
                    Logger.getLogger(Suppliermain.class.getName()).log(Level.SEVERE, null, ex);
                }
                fileHandler.setFormatter(new SimpleFormatter());
                log.addHandler(fileHandler);
            }

        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        jTextField2.setText(String.valueOf(jTable1.getValueAt(row, 0)));
        jTextField4.setText(String.valueOf(jTable1.getValueAt(row, 1)));
        jTextField3.setText(String.valueOf(jTable1.getValueAt(row, 2)));
         
        jComboBox3.setSelectedItem(String.valueOf(jTable1.getValueAt(row, 3)));
        jComboBox1.setSelectedItem(String.valueOf(jTable1.getValueAt(row, 4)));
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
