/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.gui;

/**
 *
 * @author User
 */
public class TableRowCard extends javax.swing.JPanel {

    /**
     * Creates new form TableRowCard
     */
    public TableRowCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(32767, 310));
        setMinimumSize(new java.awt.Dimension(900, 310));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 310));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
