/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.gui;

import com.cafe.model.Mysql;
import com.formdev.flatlaf.FlatClientProperties;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TableCard extends javax.swing.JPanel {

    private String id;
    private String category;
    private String Status;
    private String image;
    private TableManagement tableManagement;

    public void setTableManagement(TableManagement tableManagement) {
        this.tableManagement = tableManagement;
    }

    public TableCard() {
        initComponents();
        setStyle();
        loadTables();
    }

    public void loadTables() {
        Vector v = new Vector();

        try {
            ResultSet resultSet = Mysql.execute("SELECT `name` FROM `table_status`");

            while (resultSet.next()) {
                String name = resultSet.getString("name");
                v.add(name);
            }
            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox1.getModel();
            model.addAll(v);

        } catch (Exception ex) {
            Logger.getLogger(TableCard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(215, 300));
        setMinimumSize(new java.awt.Dimension(152, 300));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(215, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel12.setPreferredSize(new java.awt.Dimension(210, 100));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel16.setPreferredSize(new java.awt.Dimension(170, 278));
        jPanel16.setLayout(new java.awt.BorderLayout(5, 10));

        jPanel17.setPreferredSize(new java.awt.Dimension(128, 80));
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/img/Table111.png"))); // NOI18N
        jLabel1.setText("Table1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(jLabel1);

        jPanel16.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel18.setLayout(new java.awt.BorderLayout(5, 0));

        jPanel20.setLayout(new java.awt.GridLayout(3, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TBL 2-5");
        jPanel20.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Two Seater");
        jPanel20.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Avalible");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel20.add(jLabel8);

        jPanel18.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(170, 90));
        jPanel1.setLayout(new java.awt.BorderLayout(5, 10));

        jButton1.setBackground(new java.awt.Color(77, 120, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(84, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.SOUTH);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel16.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel16, java.awt.BorderLayout.CENTER);

        add(jPanel12, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String id = jLabel6.getText();
        String status = jLabel8.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Name", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Status", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String status1 = String.valueOf(jComboBox1.getSelectedItem());
                ResultSet resultSet = Mysql.execute("SELECT `id` FROM `table_status` WHERE `name` = '" + status1 + "'");

                if (resultSet.next()) {
                    String string = resultSet.getString("id");
                    Mysql.execute("UPDATE `table` SET `table_status_id` = '" + string + "'  WHERE `table`.`id` = '" + id + "'");
                    if(tableManagement != null){
                        tableManagement.getDashboard().setSuccessStatus("Table: "+id+" Status updated");
                        tableManagement.loadTables();
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "Status Can not Found", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception ex) {
                Logger.getLogger(TableCard.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Vector v = new Vector();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    // End of variables declaration//GEN-END:variables

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
        jLabel6.setText(id);

    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
        jLabel7.setText(category);
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
        jLabel8.setText(Status);
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
        jLabel1.setText(image);
    }

    private void setStyle() {
        jPanel12.putClientProperty(FlatClientProperties.STYLE, "border:10,10,10,10,#4D78CC,0,40");
        jComboBox1.putClientProperty(FlatClientProperties.STYLE, "arc: 30");
        jButton1.putClientProperty(FlatClientProperties.STYLE, "arc: 30");
    }
}
