/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.gui;

/**
 *
 * @author User
 */
public class TableManagement extends javax.swing.JPanel {

    private Dashboard dashboard;

    public Dashboard getDashboard() {
        return dashboard;
    }

    public void setDashboard(Dashboard dashboard) {
        this.dashboard = dashboard;
    }
    /**
     * Creates new form TableManagement
     */
    public TableManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel43 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel46 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel47 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 20));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout(10, 20));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jPanel4.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel7.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel29.setLayout(new java.awt.GridLayout(1, 3));

        jPanel30.setPreferredSize(new java.awt.Dimension(210, 100));
        jPanel30.setLayout(new java.awt.BorderLayout());
        jPanel30.add(jPanel11, java.awt.BorderLayout.LINE_END);
        jPanel30.add(jPanel13, java.awt.BorderLayout.PAGE_START);
        jPanel30.add(jPanel57, java.awt.BorderLayout.LINE_START);
        jPanel30.add(jPanel58, java.awt.BorderLayout.PAGE_END);

        jPanel59.setLayout(new java.awt.BorderLayout());

        jPanel60.setLayout(new java.awt.BorderLayout(5, 10));

        jPanel61.setLayout(new java.awt.GridLayout(1, 0));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/img/Table111.png"))); // NOI18N
        jLabel16.setText("Table3");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel61.add(jLabel16);

        jPanel60.add(jPanel61, java.awt.BorderLayout.PAGE_START);

        jPanel62.setLayout(new java.awt.BorderLayout(5, 30));

        jPanel63.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel63.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Table ID");
        jLabel17.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel63.add(jLabel17, java.awt.BorderLayout.CENTER);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setText("****");
        jLabel25.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel63.add(jLabel25, java.awt.BorderLayout.PAGE_END);

        jPanel62.add(jPanel63, java.awt.BorderLayout.PAGE_START);

        jPanel64.setLayout(new java.awt.BorderLayout(5, 20));

        jPanel65.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel65.setLayout(new java.awt.BorderLayout(5, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Table Category");
        jLabel18.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel65.add(jLabel18, java.awt.BorderLayout.CENTER);

        jPanel66.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel66.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Table Category");
        jLabel19.setPreferredSize(new java.awt.Dimension(37, 35));
        jPanel66.add(jLabel19, java.awt.BorderLayout.CENTER);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel26.setText("****");
        jLabel26.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel66.add(jLabel26, java.awt.BorderLayout.PAGE_END);

        jPanel65.add(jPanel66, java.awt.BorderLayout.PAGE_START);

        jPanel64.add(jPanel65, java.awt.BorderLayout.PAGE_START);

        jPanel67.setLayout(new java.awt.BorderLayout());

        jPanel68.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel68.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Table State");
        jLabel20.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel68.add(jLabel20, java.awt.BorderLayout.CENTER);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel27.setText("****");
        jLabel27.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel68.add(jLabel27, java.awt.BorderLayout.PAGE_END);

        jPanel67.add(jPanel68, java.awt.BorderLayout.PAGE_START);

        jPanel64.add(jPanel67, java.awt.BorderLayout.CENTER);

        jPanel62.add(jPanel64, java.awt.BorderLayout.CENTER);

        jPanel60.add(jPanel62, java.awt.BorderLayout.CENTER);

        jPanel59.add(jPanel60, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel59, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel30);

        jPanel31.setPreferredSize(new java.awt.Dimension(210, 100));
        jPanel31.setLayout(new java.awt.BorderLayout());
        jPanel31.add(jPanel33, java.awt.BorderLayout.PAGE_START);
        jPanel31.add(jPanel34, java.awt.BorderLayout.LINE_END);
        jPanel31.add(jPanel35, java.awt.BorderLayout.LINE_START);
        jPanel31.add(jPanel41, java.awt.BorderLayout.PAGE_END);

        jPanel42.setLayout(new java.awt.BorderLayout());

        jPanel25.setLayout(new java.awt.BorderLayout(5, 10));

        jPanel26.setLayout(new java.awt.GridLayout(1, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/img/Table111.png"))); // NOI18N
        jLabel6.setText("Table2");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel26.add(jLabel6);

        jPanel25.add(jPanel26, java.awt.BorderLayout.PAGE_START);

        jPanel27.setLayout(new java.awt.BorderLayout(5, 30));

        jPanel28.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Table ID");
        jLabel7.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel28.add(jLabel7, java.awt.BorderLayout.CENTER);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("****");
        jLabel22.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel28.add(jLabel22, java.awt.BorderLayout.PAGE_END);

        jPanel27.add(jPanel28, java.awt.BorderLayout.PAGE_START);

        jPanel32.setLayout(new java.awt.BorderLayout(5, 20));

        jPanel36.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel36.setLayout(new java.awt.BorderLayout(5, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Table Category");
        jLabel8.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel36.add(jLabel8, java.awt.BorderLayout.CENTER);

        jPanel37.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel37.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Table Category");
        jLabel9.setPreferredSize(new java.awt.Dimension(37, 35));
        jPanel37.add(jLabel9, java.awt.BorderLayout.CENTER);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setText("****");
        jLabel23.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel37.add(jLabel23, java.awt.BorderLayout.PAGE_END);

        jPanel36.add(jPanel37, java.awt.BorderLayout.PAGE_START);

        jPanel32.add(jPanel36, java.awt.BorderLayout.PAGE_START);

        jPanel38.setLayout(new java.awt.BorderLayout());

        jPanel39.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel39.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Table State");
        jLabel10.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel39.add(jLabel10, java.awt.BorderLayout.CENTER);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setText("****");
        jLabel24.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel39.add(jLabel24, java.awt.BorderLayout.PAGE_END);

        jPanel38.add(jPanel39, java.awt.BorderLayout.PAGE_START);

        jPanel32.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel27.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel27, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel31.add(jPanel42, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel31);

        jPanel12.setPreferredSize(new java.awt.Dimension(210, 100));
        jPanel12.setLayout(new java.awt.BorderLayout());
        jPanel12.add(jPanel6, java.awt.BorderLayout.PAGE_START);
        jPanel12.add(jPanel8, java.awt.BorderLayout.LINE_END);
        jPanel12.add(jPanel14, java.awt.BorderLayout.LINE_START);
        jPanel12.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        jPanel16.setLayout(new java.awt.BorderLayout(5, 10));

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/img/Table111.png"))); // NOI18N
        jLabel1.setText("Table1");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(jLabel1);

        jPanel16.add(jPanel17, java.awt.BorderLayout.PAGE_START);

        jPanel18.setLayout(new java.awt.BorderLayout(5, 30));

        jPanel19.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Table ID");
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel19.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("****");
        jLabel14.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel19.add(jLabel14, java.awt.BorderLayout.PAGE_END);

        jPanel18.add(jPanel19, java.awt.BorderLayout.PAGE_START);

        jPanel20.setLayout(new java.awt.BorderLayout(5, 20));

        jPanel21.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel21.setLayout(new java.awt.BorderLayout(5, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Table Category");
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel21.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel23.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel23.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Table Category");
        jLabel4.setPreferredSize(new java.awt.Dimension(37, 35));
        jPanel23.add(jLabel4, java.awt.BorderLayout.CENTER);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("****");
        jLabel15.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel23.add(jLabel15, java.awt.BorderLayout.PAGE_END);

        jPanel21.add(jPanel23, java.awt.BorderLayout.PAGE_START);

        jPanel20.add(jPanel21, java.awt.BorderLayout.PAGE_START);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jPanel24.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel24.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Table State");
        jLabel5.setPreferredSize(new java.awt.Dimension(37, 40));
        jPanel24.add(jLabel5, java.awt.BorderLayout.CENTER);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("****");
        jLabel21.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel24.add(jLabel21, java.awt.BorderLayout.PAGE_END);

        jPanel22.add(jPanel24, java.awt.BorderLayout.PAGE_START);

        jPanel20.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel12);

        jPanel10.add(jPanel29, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel10, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Table View", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel48.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel40.setPreferredSize(new java.awt.Dimension(160, 100));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("Add");
        jButton1.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel40.add(jButton1, java.awt.BorderLayout.SOUTH);

        jPanel48.add(jPanel40, java.awt.BorderLayout.LINE_END);

        jPanel43.setPreferredSize(new java.awt.Dimension(160, 100));
        jPanel43.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Name");
        jLabel11.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel43.add(jLabel11, java.awt.BorderLayout.CENTER);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField3.setText("###");
        jTextField3.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel43.add(jTextField3, java.awt.BorderLayout.PAGE_END);

        jPanel48.add(jPanel43, java.awt.BorderLayout.LINE_START);

        jPanel44.setPreferredSize(new java.awt.Dimension(120, 100));
        jPanel44.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel45.setPreferredSize(new java.awt.Dimension(145, 100));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Amount");
        jLabel13.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel45.add(jLabel13, java.awt.BorderLayout.CENTER);

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField9.setText("###");
        jTextField9.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel45.add(jTextField9, java.awt.BorderLayout.PAGE_END);

        jPanel44.add(jPanel45, java.awt.BorderLayout.LINE_END);

        jPanel46.setPreferredSize(new java.awt.Dimension(145, 100));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Capacity");
        jLabel12.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel46.add(jLabel12, java.awt.BorderLayout.CENTER);

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField8.setText("###");
        jTextField8.setPreferredSize(new java.awt.Dimension(43, 40));
        jPanel46.add(jTextField8, java.awt.BorderLayout.PAGE_END);

        jPanel44.add(jPanel46, java.awt.BorderLayout.LINE_START);

        jPanel48.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel48, java.awt.BorderLayout.PAGE_START);

        jPanel47.setLayout(new java.awt.BorderLayout(5, 5));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Capacity", "Avalible amount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel47.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel28.setText("Table list");
        jPanel47.add(jLabel28, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(jPanel47, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Manage", jPanel5);

        jPanel3.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
